/* Auto-generated by genmsg_cpp for file /home/omid/my_workspace/SLAM/msg/SFM_msg.msg */
#ifndef SLAM_MESSAGE_SFM_MSG_H
#define SLAM_MESSAGE_SFM_MSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "sensor_msgs/Image.h"

namespace SLAM
{
template <class ContainerAllocator>
struct SFM_msg_ {
  typedef SFM_msg_<ContainerAllocator> Type;

  SFM_msg_()
  : header()
  , size(0)
  , P()
  , image()
  {
  }

  SFM_msg_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , size(0)
  , P(_alloc)
  , image(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint32_t _size_type;
  uint32_t size;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _P_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  P;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
   ::sensor_msgs::Image_<ContainerAllocator>  image;


  typedef boost::shared_ptr< ::SLAM::SFM_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::SLAM::SFM_msg_<ContainerAllocator>  const> ConstPtr;
}; // struct SFM_msg
typedef  ::SLAM::SFM_msg_<std::allocator<void> > SFM_msg;

typedef boost::shared_ptr< ::SLAM::SFM_msg> SFM_msgPtr;
typedef boost::shared_ptr< ::SLAM::SFM_msg const> SFM_msgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::SLAM::SFM_msg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::SLAM::SFM_msg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace SLAM

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::SLAM::SFM_msg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::SLAM::SFM_msg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::SLAM::SFM_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0f7da4217e07aa4196e821a466e25362";
  }

  static const char* value(const  ::SLAM::SFM_msg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0f7da4217e07aa41ULL;
  static const uint64_t static_value2 = 0x96e821a466e25362ULL;
};

template<class ContainerAllocator>
struct DataType< ::SLAM::SFM_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "SLAM/SFM_msg";
  }

  static const char* value(const  ::SLAM::SFM_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::SLAM::SFM_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint32 size\n\
float32[] P\n\
sensor_msgs/Image image\n\
\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
";
  }

  static const char* value(const  ::SLAM::SFM_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::SLAM::SFM_msg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::SLAM::SFM_msg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::SLAM::SFM_msg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.size);
    stream.next(m.P);
    stream.next(m.image);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SFM_msg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::SLAM::SFM_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::SLAM::SFM_msg_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "size: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.size);
    s << indent << "P[]" << std::endl;
    for (size_t i = 0; i < v.P.size(); ++i)
    {
      s << indent << "  P[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.P[i]);
    }
    s << indent << "image: ";
s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SLAM_MESSAGE_SFM_MSG_H

